namespace Avalonia.Media.Fonts.Rasterization.TrueType
{
    /// <summary>Human-readable opcode names for the interpreter's trace hook.</summary>
    internal static class TrueTypeOpcodeName
    {
        public static string Of(byte opcode) => opcode switch
        {
            0x00 => "SVTCA[y]",
            0x01 => "SVTCA[x]",
            0x02 => "SPVTCA[y]",
            0x03 => "SPVTCA[x]",
            0x04 => "SFVTCA[y]",
            0x05 => "SFVTCA[x]",
            0x06 or 0x07 => "SPVTL",
            0x08 or 0x09 => "SFVTL",
            0x0A => "SPVFS",
            0x0B => "SFVFS",
            0x0C => "GPV",
            0x0D => "GFV",
            0x0E => "SFVTPV",
            0x0F => "ISECT",
            0x10 => "SRP0",
            0x11 => "SRP1",
            0x12 => "SRP2",
            0x13 => "SZP0",
            0x14 => "SZP1",
            0x15 => "SZP2",
            0x16 => "SZPS",
            0x17 => "SLOOP",
            0x18 => "RTG",
            0x19 => "RTHG",
            0x1A => "SMD",
            0x1B => "ELSE",
            0x1C => "JMPR",
            0x1D => "SCVTCI",
            0x1E => "SSWCI",
            0x1F => "SSW",
            0x20 => "DUP",
            0x21 => "POP",
            0x22 => "CLEAR",
            0x23 => "SWAP",
            0x24 => "DEPTH",
            0x25 => "CINDEX",
            0x26 => "MINDEX",
            0x27 => "ALIGNPTS",
            0x29 => "UTP",
            0x2A => "LOOPCALL",
            0x2B => "CALL",
            0x2C => "FDEF",
            0x2D => "ENDF",
            0x2E => "MDAP[0]",
            0x2F => "MDAP[1]",
            0x30 => "IUP[y]",
            0x31 => "IUP[x]",
            0x32 or 0x33 => "SHP",
            0x34 or 0x35 => "SHC",
            0x36 or 0x37 => "SHZ",
            0x38 => "SHPIX",
            0x39 => "IP",
            0x3A or 0x3B => "MSIRP",
            0x3C => "ALIGNRP",
            0x3D => "RTDG",
            0x3E => "MIAP[0]",
            0x3F => "MIAP[1]",
            0x40 => "NPUSHB",
            0x41 => "NPUSHW",
            0x42 => "WS",
            0x43 => "RS",
            0x44 => "WCVTP",
            0x45 => "RCVT",
            0x46 or 0x47 => "GC",
            0x48 => "SCFS",
            0x49 or 0x4A => "MD",
            0x4B => "MPPEM",
            0x4C => "MPS",
            0x4D => "FLIPON",
            0x4E => "FLIPOFF",
            0x4F => "DEBUG",
            0x50 => "LT",
            0x51 => "LTEQ",
            0x52 => "GT",
            0x53 => "GTEQ",
            0x54 => "EQ",
            0x55 => "NEQ",
            0x56 => "ODD",
            0x57 => "EVEN",
            0x58 => "IF",
            0x59 => "EIF",
            0x5A => "AND",
            0x5B => "OR",
            0x5C => "NOT",
            0x5D => "DELTAP1",
            0x5E => "SDB",
            0x5F => "SDS",
            0x60 => "ADD",
            0x61 => "SUB",
            0x62 => "DIV",
            0x63 => "MUL",
            0x64 => "ABS",
            0x65 => "NEG",
            0x66 => "FLOOR",
            0x67 => "CEILING",
            >= 0x68 and <= 0x6B => "ROUND",
            >= 0x6C and <= 0x6F => "NROUND",
            0x70 => "WCVTF",
            0x71 => "DELTAP2",
            0x72 => "DELTAP3",
            0x73 => "DELTAC1",
            0x74 => "DELTAC2",
            0x75 => "DELTAC3",
            0x76 => "SROUND",
            0x77 => "S45ROUND",
            0x78 => "JROT",
            0x79 => "JROF",
            0x7A => "ROFF",
            0x7C => "RUTG",
            0x7D => "RDTG",
            0x7E => "SANGW",
            0x7F => "AA",
            0x80 => "FLIPPT",
            0x81 => "FLIPRGON",
            0x82 => "FLIPRGOFF",
            0x85 => "SCANCTRL",
            0x86 or 0x87 => "SDPVTL",
            0x88 => "GETINFO",
            0x89 => "IDEF",
            0x8A => "ROLL",
            0x8B => "MAX",
            0x8C => "MIN",
            0x8D => "SCANTYPE",
            0x8E => "INSTCTRL",
            >= 0xB0 and <= 0xB7 => "PUSHB",
            >= 0xB8 and <= 0xBF => "PUSHW",
            >= 0xC0 and <= 0xDF => "MDRP",
            >= 0xE0 => "MIRP",
            _ => "UNKNOWN",
        };
    }
}
