<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(AvsCurrentTargetFramework);$(AvsLegacyTargetFrameworks)</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup Label="InternalsVisibleTo">
    <InternalsVisibleTo Include="Avalonia.CoreText.UnitTests, PublicKey=$(AvaloniaPublicKey)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Avalonia.Base\Avalonia.Base.csproj" />
    <ProjectReference Include="..\..\Avalonia.Controls\Avalonia.Controls.csproj" />
  </ItemGroup>
  <Import Project="..\..\..\build\BuildTargets.targets" />
  <Import Project="..\..\..\build\NullableEnable.props" />
</Project>
